#!/usr/bin/env python3
"""
Strict name extractor for HTR death records.
Only returns names that look like actual person names.
"""
import re

# Common locations, titles, and noise that should NEVER be names
NOISE_WORDS = {
    'villa', 'vila', 'igreja', 'igrejas', 'capella', 'capelas', 'collegiada',
    'bispado', 'arquivo', 'distrito', 'freguesia', 'freguesias',
    'cemiterio', 'cemitério', 'sepultura', 'sepultamento', 'sepultado',
    'assento', 'assentos', 'livro', 'livros', 'folhas', 'folha',
    'defuntos', 'corpo', 'cadver', 'cadaver', 'morte', 'morto', 'morta',
    'sacramento', 'sacramentos', 'batismo', 'casamento', 'obito', 'óbito',
    'testamento', 'testamentos', 'herdeiro', 'herdeira', 'legado',
    'eram', 'desta', 'deste', 'desse', 'dessa', 'nesta', 'neste',
    'aos', 'era', 'anno', 'anos', 'annos', 'idade', 'meses', 'dias',
    'janeiro', 'fevereiro', 'março', 'marco', 'abril', 'maio', 'junho',
    'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro',
    'santa', 'santo', 'santos', 'sancta', 'senhora', 'senhor',
    'padre', 'reverendo', 'vigario', 'vigário', 'cura', 'prior',
    'arcipreste', 'beneficiado', 'mordomo', 'juiz', 'escrivão',
    'encomendado', 'provisor', 'vigairo',
    'matriz', 'collegio', 'colégio', 'convento', 'mosteiro',
    'ermida', 'cathedral', 'catedral', 'parochia', 'paróquia',
    'oratorio', 'oratório', 'capellao', 'capelão', 'coadjuctor',
    'coadjutor', 'sacristao', 'sacristã', 'sacristia',
    'celorico', 'celoricense', 'beirense', 'guarda', 'guarda',
    'portugal', 'Portugal', 'Portugal', 'reinado', 'el-rei', 'el rei',
    'magestade', 'majestade',
    'mes', 'mez', 'mezes',
    'primo', 'prima', 'primos', 'primas',
    'irmaos', 'irmaãs', 'irmao', 'irmaã', 'irmaos', 'irman', 'irmandade',
    'neto', 'neta', 'netos', 'netas',
    'sobrinho', 'sobrinha', 'sobrinhos', 'sobrinhas',
    'tio', 'tia', 'tios', 'tias',
    'avo', 'avos', 'avó', 'avô',
    'cunhado', 'cunhada', 'cunhados', 'cunhadas',
    'genro', 'nora', 'genros', 'noras',
    'padrasto', 'madrasta', 'padrasta', 'madrasta',
    'enteado', 'enteada',
    'afilhado', 'afilhada', 'afilhados', 'afilhadas',
    'compadre', 'comadre',
    'vizinho', 'vizinha', 'vizinhos', 'vizinhas',
    'proximo', 'proxima', 'proximos', 'proximas',
    'amigo', 'amiga', 'amigos', 'amigas',
    'parente', 'parentes', 'parentesco',
    'domestico', 'domestica', 'doméstico', 'doméstica',
    'criado', 'criada', 'criados', 'criadas',
    'escravo', 'escrava', 'escravos', 'escravas',
    ' servo', 'serva', 'servos', 'servas',
    'fiel', 'fieis', 'crente',
    'alma', 'almas',
    'corpo', 'corpos',
    'casa', 'casas',
    'quinta', 'quintas',
    'horta', 'hortas',
    'jardim', 'jardins',
    'camara', 'câmara', 'camaras',
    'verdade', 'verdadeiro',
    'justica', 'justiça', 'justiças',
    'direito', 'direitos',
    'lei', 'leis',
    'costume', 'costumes',
    'uso', 'usos',
    'praxe', 'praxes',
    'cerimonia', 'cerimónia',
    'culto', 'cultos',
    'missa', 'missas',
    'funcção', 'função',
    'officio', 'ofício', 'officios',
    'serviço', 'serviços',
    'ministro', 'ministros',
    'autoridade', 'autoridades',
    'poder', 'poderes',
    'governo', 'governos',
    'estado', 'estados',
    'reino', 'reinos',
    'imperio', 'império',
    'monarcha', 'monarca', 'monarchia', 'monarquia',
    'rei', 'rainha', 'reis', 'rainhas',
    'principe', 'princesa', 'principes', 'princesas',
    'infante', 'infantes',
    'duque', 'duquesa', 'duques', 'duquesas',
    'conde', 'condessa', 'condes', 'condessas',
    'marquez', 'marquês', 'marqueza', 'marquesas',
    'visconde', 'viscondessa',
    'barão', 'baroneza',
    'graõ', 'grão', 'grande', 'grandes',
    'excellencia', 'excelência',
    'senhoria', 'senhorias',
    'ilustrissimo', 'ilustríssimo',
    'muito', 'muitos', 'muita', 'muitas',
    'devoto', 'devota', 'devotos', 'devotas',
    'cristão', 'cristã', 'cristãos', 'cristãs',
    'fiel', 'fieis', 'fiel',
    'crente', 'crentes',
    'irmão', 'irmã', 'irmaos', 'irmaãs',
    'irmaos', 'irmaã',
    'companheiro', 'companheira', 'companheiros', 'companheiras',
    'amigo', 'amiga', 'amigos', 'amigas',
    'conhecido', 'conhecida', 'conhecidos', 'conhecidas',
    'vizinho', 'vizinha', 'vizinhos', 'vizinhas',
    'proximo', 'proxima', 'proximos', 'proximas',
    'parente', 'parentes',
    'familia', 'família', 'familias', 'famílias',
    'linhagem', 'geração', 'gerações', 'geracoes',
    'descendencia', 'descendência',
    'ascendencia', 'ascendência',
    'genealogia', 'genealogias',
    'historia', 'história', 'historias', 'histórias',
    'chronicas', 'crônicas',
    'memorias', 'memórias',
    'noticia', 'notícia', 'noticias', 'notícias',
    'descripção', 'descripçao', 'descrição', 'descricao',
    'relaçao', 'relação',
    'conta', 'contas',
    'nome', 'nomes',
    'sobrenome', 'sobrenomes', 'apelido', 'apelidos',
    'alcunha', 'alcunhas',
    'signatura', 'signaturas',
    'assinatura', 'assinaturas',
    'escrito', 'escrita', 'escritos', 'escritas',
    'dito', 'dita', 'ditos', 'ditas',
    'dita', 'dito',
    'testemunha', 'testemunhas',
    'testador', 'testadora',
    'testamenteiro', 'testamenteira',
    'inventariante',
    'inventario', 'inventário',
    'partilha', 'partilhas',
    'divisão', 'divisao', 'divisoes',
    'herança', 'heranças',
    'legado', 'legados',
    'doaçao', 'doação', 'doacoes', 'doações',
    'doa', 'doou',
    'deixou', 'deixaram', 'deixou-lhe', 'deixou-me',
    'mandou', 'mandaram',
    'ordenou', 'ordenaram',
    'pediu', 'pediram',
    'rogou', 'rogaram',
    'suplicou', 'suplicaram',
    'desejou', 'desejaram',
    'quis', 'quiseram', 'quiser', 'queira',
    'consentiu', 'consentiram',
    'permitiu', 'permitiram',
    'autorizou', 'autorizaram',
    'determinou', 'determinaram',
    'estabeleceu', 'estabeleceram',
    'dispoz', 'dispôs', 'dispozeram', 'dispunha',
    'ordenou', 'ordenaram',
    'constituiu', 'constituiram',
    'nomeou', 'nomearam',
    'escolheu', 'escolheram',
    'designou', 'designaram',
    'indicou', 'indicaram',
    'apontou', 'apontaram',
    'mencionou', 'mencionaram',
    'referiu', 'referiram',
    'citou', 'citaram',
    'nomeia', 'nomeiam',
    'chama', 'chamam',
    'diz', 'dizem',
    'conhece', 'conhecem',
    'sabe', 'sabem',
    'crê', 'creem', 'creu', 'creram',
    'acredita', 'acreditam',
    'firma', 'firmam',
    'jura', 'juram',
    'promete', 'prometem',
    'obriga', 'obrigam',
    'compromete', 'comprometem',
    'assinado', 'assinada', 'assinados', 'assinadas',
    'rubricado', 'rubricada', 'rubricados', 'rubricadas',
    'numerado', 'numerada', 'numerados', 'numeradas',
    'lavrado', 'lavrada', 'lavrados', 'lavradas',
    'escrito', 'escrita', 'escritos', 'escritas',
    'passado', 'passada', 'passados', 'passadas',
    'dado', 'dada', 'dados', 'dadas',
    'feito', 'feita', 'feitos', 'feitas',
    'tratado', 'tratada', 'tratados', 'tratadas',
    'pregado', 'pregada', 'pregados', 'pregadas',
    'doutrinado', 'doutrinada',
    'ensinado', 'ensinada',
    'instruido', 'instruida',
    'educado', 'educada',
    'criado', 'criada',
    'nascido', 'nascida', 'nascidos', 'nascidas',
    'batizado', 'batizada', 'batizados', 'batizadas',
    'casado', 'casada', 'casados', 'casadas',
    'desposado', 'desposada',
    'noivado', 'noivada',
    'viuvo', 'viuva', 'viuvos', 'viuvas',
    'separado', 'separada',
    'divorciado', 'divorciada',
    'solteiro', 'solteira', 'solteiros', 'solteiras',
    'casadoiro', 'casadoira',
    'desposorio', 'desposória',
    'matrimonio', 'matrimónio', 'matrimonios',
    'boda', 'bodas',
    'nupcias', 'núpcias',
    'festejo', 'festejos',
    'celebração', 'celebraçao', 'celebracoes', 'celebrações',
    'cerimonia', 'cerimónia', 'cerimonias', 'cerimónias',
    'ritual', 'rituais',
    'liturgia', 'liturgias',
    'culto', 'cultos',
    'missa', 'missas',
    'sermão', 'sermao', 'sermões',
    'pregação', 'pregaçao',
    'doutrina', 'doutrinas',
    'evangelho', 'evangelhos',
    'epistola', 'epístola',
    'leitura', 'leituras',
    'canção', 'cancao', 'canções', 'cancões',
    'hino', 'hinos',
    'salmo', 'salmos',
    'padre', 'padres',
    'vigario', 'vigários',
    'cura', 'curas',
    'bispo', 'bispos',
    'arcebispo', 'arcebispos',
    'cardeal', 'cardeais',
    'papa', 'papas',
    'monge', 'monges',
    'frade', 'frades',
    'monge', 'monges',
    'religioso', 'religiosa', 'religiosos', 'religiosas',
    'freira', 'freiras', 'freire', 'freires',
    'noviço', 'noviça', 'noviços', 'noviças',
    'professo', 'professa',
    'jubilado', 'jubilada',
    'emerito', 'emerita',
    'beneficiado', 'beneficiada',
    'renda', 'rendas',
    'beneficio', 'benefícios',
    'pensão', 'pensões',
    'moradia', 'moradias',
    'estalagem', 'estalagens',
    'pensão', 'pensoes',
    'hospedagem', 'hospedagens',
    'hospedaria', 'hospedarias',
    'estalajem', 'estalajens',
    'albergue', 'albergues',
    'abrigo', 'abrigos',
    'refugio', 'refúgio', 'refugios', 'refúgios',
    'casa', 'casas',
    'morada', 'moradas',
    'residencia', 'residência', 'residencias',
    'domicilio', 'domicílio', 'domicilios', 'domicílios',
    'habitação', 'habitacao', 'habitacoes', 'habitações',
    'fogo', 'fogos',
    'lume', 'lumes',
    'lar', 'lares',
    'tecto', 'tectos', 'teto', 'tetos',
    'telhado', 'telhados',
    'porta', 'portas',
    'janela', 'janelas',
    'chaminé', 'chamine', 'chaminés',
    'escada', 'escadas',
    'corredor', 'corredores',
    'sala', 'salas',
    'quarto', 'quartos',
    'alcova', 'alcovas',
    'cama', 'camas',
    'cadeira', 'cadeiras',
    'mesa', 'mesas',
    'bancos', 'banco',
    'bau', 'baús',
    'baú', 'baus',
    'arcaz', 'arca',
    'cómoda', 'commodas', 'cômoda',
    'espelho', 'espelhos',
    'quadro', 'quadros',
    'imagem', 'imagens',
    'estatua', 'estátua', 'estatuas', 'estátuas',
    'figura', 'figuras',
    'relevo', 'relevos',
    'medalha', 'medalhas',
    'moeda', 'moedas',
    'pulseira', 'pulseiras',
    'anel', 'aneis', 'anéis',
    'brinco', 'brincos',
    'colar', 'colares',
    'corrente', 'correntes',
    'fio', 'fios',
    'linha', 'linhas',
    'agulha', 'agulhas',
    'alfinete', 'alfinetes',
    'botão', 'botões', 'botao', 'botoes',
    'fivela', 'fivelas',
    'fecho', 'fechos',
    'fechadura', 'fechaduras',
    'chave', 'chaves',
    'cadeado', 'cadeados',
    'ferrolho', 'ferrolhos',
    'trinco', 'trincos',
    'maçaneta', 'maçanetas',
    'puxador', 'puxadores',
    'batente', 'batentes',
    'campainha', 'campainhas',
    'sino', 'sinos',
    'relogio', 'relógio', 'relogios', 'relógios',
    'ampulheta', 'ampulhetas',
    'calendario', 'calendário',
    'ponteiro', 'ponteiros',
    'mecanismo', 'mecanismos',
    'function', 'funciona',
    'pedra', 'pedras',
    'marmore', 'mármore',
    'granito', 'granitos',
    'cal', 'cales',
    'areia', 'areias',
    'telha', 'telhas',
    'madeira', 'madeiras',
    'carvalho', 'carvalhos',
    'pinho', 'pinhos',
    'castanho', 'castanha',
    'carvalho', 'sobreiro',
    'azinheiro', 'azinheiras',
    'oliveira', 'oliveiras',
    'figueira', 'figueiras',
    'parreiral', 'parreiras',
    'videira', 'videiras',
    'laranjeira', 'laranjeiras',
    'limoeiro', 'limoeiros',
    'roseira', 'roseiras',
    'jardim', 'jardins',
    'flor', 'flores',
    'erva', 'ervas',
    'relva', 'relvas',
    'matagal', 'matagais',
    'bosque', 'bosques',
    'selva', 'selvas',
    'floresta', 'florestas',
    'pinhal', 'pinhais',
    'monte', 'montes', 'monte',
    'serra', 'serras',
    'colina', 'colinas',
    'vale', 'vales',
    'ribeira', 'ribeiras',
    'rio', 'rios',
    'ribeiro', 'ribeiros',
    'córrego', 'corrego', 'córregos', 'corregos',
    'regato', 'regatos',
    'fonte', 'fontes',
    'poço', 'poços',
    'nascente', ' nascentes',
    'cachoeira', 'cachoeiras',
    'queda', 'quedas',
    'lago', 'lagos',
    'lagoa', 'lagoas',
    'mar', 'mares',
    'praia', 'praias',
    'ilha', 'ilhas',
    'ilhéu', 'ilhoes',
    'ilheu', 'ilheus',
    'rocha', 'rochas',
    'gruta', 'grutas',
    'caverna', 'cavernas',
    'buraco', 'buracos',
    'fenda', 'fendas',
    'brecha', 'brechas',
    'desfiladeiro', 'desfiladeiros',
    'abismo', 'abismos',
    'precipicio', 'precipício',
    'cume', 'cumes',
    'cimo', 'cimos',
    'topo', 'topos',
    'pico', 'picos',
    'montanha', 'montanhas',
    'cordilheira', 'cordilheiras',
    'planalto', 'planaltos',
    'planicie', 'planicies',
    'campina', 'campinas',
    'campo', 'campos',
    'prado', 'prados',
    'pasto', 'pastos',
    'cultura', 'culturas',
    'lavoura', 'lavouras',
    'seara', 'searas',
    'vinha', 'vinhas',
    'olival', 'olivais',
    'pomar', 'pomares',
    'horta', 'hortas',
    'jardim', 'jardins',
    'bosque', 'bosques',
    'mata', 'matas',
    'selva', 'selvas',
    'floresta', 'florestas',
    'pinhal', 'pinhais',
    'montado', 'montados',
    'sobro', 'sobr',
    'azinheira', 'azinheiras',
    'castinhal', 'castinhais',
    'eucalipto', 'eucaliptos',
    'acácia', 'acacias',
    'pinheiro', 'pinheiros',
    'cedro', 'cedros',
    'carvalho', 'carvalhos',
    'sobreiro', 'sobreiros',
    'azinheiro', 'azinheiros',
    'oliveira', 'oliveiras',
    'figueira', 'figueiras',
    'vides', 'parreiras',
    'videira', 'videiras',
    'laranjeira', 'laranjeiras',
    'limoeiro', 'limoeiros',
    'roseira', 'roseiras',
    'jasmineiro', 'jasmineiros',
    'magnolia', 'magnolias',
    'palmeira', 'palmeiras',
    'pinha', 'pinhas',
    'pinha', 'pinhos',
    'agulha', 'agulhas',
    'espinho', 'espinhos',
    'rosa', 'rosas', 'rosel',
    'jasmim', 'jasmins',
    'margarida', 'margaridas',
    'cravo', 'cravos',
    'tulipa', 'tulipas',
    'orquidea', 'orquideas',
    'violeta', 'violetas',
    'lirio', 'lirios',
    'craveiro', 'craveiros',
    'geranio', 'geranios',
    'sardinheiro', 'sardinheiros',
    'arraya', 'arrayas',
    'verbena', 'verbenas',
    'hortelã', 'hortela',
    'hortelao', 'hortelães',
    'rosmarinho', 'rosmarinhos',
    'tomilho', 'tomilhos',
    'salva', 'salb',
    'alecrim', 'alecrins',
    'lavanda', 'lavandas',
    'rosmaninho', 'rosmaninhos',
    'poejo', 'poejos',
    'menta', 'mentas',
    'erva-doce', 'ervas-doces',
    'aniz', 'anis',
    'canela', 'canelas',
    'cravo-da-india', 'cravos-da-india',
    'noz-moscada', 'nozes-moscadas',
    'pimenta', 'pimentas',
    'sal', 'sais',
    'açucar', 'açucares',
    'acucar', 'mel',
    'manteiga', 'manteigas',
    'queijo', 'queijos',
    'leite', 'leites',
    'mijo', 'mijo',
    'água', 'agua', 'aguas', 'águas',
    'vinho', 'vinhos',
    'azeite', 'azeites',
    'vinagre', 'vinagres',
    'casa', 'casas', 'casa',
    'palacio', 'palácio', 'palacios', 'palácios',
    'castelo', 'castelos',
    'fortaleza', 'fortalezas',
    'muralha', 'muralhas',
    'torre', 'torres',
    'campanario', 'campanários',
    'torreao', 'torreões',
    'torra', 'torre',
    'torres', 'torres',
    'ala', 'alas',
    'quarto', 'quartos',
    'sala', 'salas',
    'salão', 'salao', 'salas',
    'salão', 'salao',
    'comedor', 'comedores',
    'despensa', 'despensas',
    'cozinha', 'cozinhas',
    'fogao', 'fogões', 'fogao', 'fogoes',
    'forno', 'fornos',
    'lareira', 'lareiras',
    'chamine', 'chaminés', 'chamine',
    'chaminé', 'chamines',
    'escadas', 'escada',
    'patamar', 'patamares',
    'corredor', 'corredores',
    'passagem', 'passagens',
    'tuneis', 'túneis',
    'tunel', 'túnel',
    'arco', 'arcos',
    'fronteira', 'fronteiras',
    'porta', 'portas',
    'portal', 'portais',
    'postigo', 'postigos',
    'janela', 'janelas',
    'gelosia', 'gelosias',
    'persiana', 'persianas',
    'cortina', 'cortinas',
    'reposteiro', 'reposteiros',
    'pano', 'panos', 'pano',
    'tecido', 'tecidos',
    'lã', 'las', 'la',
    'seda', 'sedas',
    ' algodão', ' algodao', ' algodões',
    'linho', 'linhos',
    'canhamo', 'cânhamo',
    'la', 'las',
    'fio', 'fios',
    'fio', 'fios',
    'bobine', 'bobines',
    'carretel', 'carreteis',
    'novelo', 'novelos',
    'meada', 'meadas',
    'fuso', 'fusos',
    'roca', 'rocas',
    'tear', 'teares',
    'tecelagem', 'tecelagens',
    'pano', 'panos',
    'roupa', 'roupas',
    'roupão', 'roupoẽs',
    'manto', 'mantos',
    'capa', 'capas',
    'capuz', 'capuzes',
    'gorro', 'gorros',
    'barrete', 'barretes',
    'chapeu', 'chapéu', 'chapéus',
    'chapeo', 'chapeos',
    'sombreiro', 'sombreiros',
    'leve', 'leves',
    'pesado', 'pesados',
    'fino', 'finos',
    'grosso', 'grossos',
    'largo', 'largos',
    'apertado', 'apertados',
    'curto', 'curtos',
    'comprido', 'compridos',
    'cumprido', 'cumpridos',
    'comprimento', 'comprimentos',
    'largura', 'larguras',
    'altura', 'alturas',
    'profundidade', 'profundidades',
    'dimensão', 'dimensoes', 'dimensões',
    'medida', 'medidas',
    'peso', 'pesos',
    'massa', 'massas',
    'volume', 'volumes',
    'capacidade', 'capacidades',
    'quantidade', 'quantidades',
    'numero', 'números', 'numero',
    'número',
    'algarismo', 'algarismos',
    'digito', 'dígito', 'digitos', 'dígitos',
    'letra', 'letras',
    'palavra', 'palavras',
    'frase', 'frases',
    'periodo', 'períodos',
    'pontuacao', 'pontuação',
    'virgula', 'vírgula',
    'ponto', 'pontos',
    'ponto-final', 'pontos-finais',
    'exclamacao', 'exclamação',
    'interrogacao', 'interrogação',
    'aspas', 'aspas',
    'parêntese', 'parenteses',
    'colchete', 'colchetes',
    'chave', 'chaves',
    'barra', 'barras',
    'traço', 'traços',
    'hífen', 'hifens',
    'sublinhado', 'sublinha',
    'italico', 'itálico',
    'negrito', 'negritos',
    'sublinha', 'sublinhas',
    'maiuscula', 'maiúscula',
    'minuscula', 'minúscula',
    'capital', 'capitais',
    'versal', 'versais',
    'letra', 'letras',
    'tipo', 'tipos',
    'fonte', 'fontes',
    'imprensa', 'imprensas',
    'estamparia', 'estamparia',
    'oficina', 'oficinas',
    'trabalho', 'trabalhos',
    'obra', 'obras',
    'serviço', 'serviços',
    'servico', 'servicos',
    'tarefa', 'tarefas',
    'função', 'funcao',
    'emprego', 'empregos',
    'cargo', 'cargos',
    'posta', 'postas',
    'promocao', 'promoção',
    'promocao', 'promoções',
    'subida', 'subidas',
    'descer', 'desce',
    'cair', 'caiu',
    'levantar', 'levantou',
    'pegar', 'pegou',
    'soltar', 'soltou',
    'segurar', 'segurou',
    'largar', 'largou',
    'abrir', 'abriu',
    'fechar', 'fechou',
    'entrar', 'entrou',
    'sair', 'saiu',
    'ficar', 'ficou',
    'ir', 'foi',
    'vir', 'veio',
    'voltar', 'voltou',
    'ficar', 'ficou',
    'estar', 'esteve',
    'haver', 'houve',
    'ter', 'teve',
    'ser', 'foi',
    'estar', 'está',
    'ficar', 'fica',
    'andar', 'anda',
    'correr', 'corre',
    'andar', 'anda',
    'passar', 'passou',
    'chegar', 'chegou',
    'partir', 'partiu',
    'viajar', 'viajou',
    'caminhar', 'caminhou',
    'marchar', 'marchou',
    'desfilar', 'desfilou',
    'correr', 'corre',
    'saltar', 'saltou',
    'pular', 'pulou',
    'dançar', 'dançou',
    'cantar', 'cantou',
    'tocar', 'tocou',
    'ouvir', 'ouviu',
    'ver', 'viu',
    'olhar', 'olhou',
    'olhos', 'olho',
    'vista', 'vistas',
    'visão', 'visao', 'visões',
    'visao', 'visões',
    'cena', 'cenas',
    'vista', 'vistas',
    'paisagem', 'paisagens',
    'panorama', 'panoramas',
    'quadro', 'quadros',
    'pintura', 'pinturas',
    'desenho', 'desenhos',
    'escultura', 'esculturas',
    'estatua', 'estátua', 'estatuas',
    'figura', 'figuras',
    'forma', 'formas',
    'figura', 'figuras',
    'imagem', 'imagens',
    'figura', 'figuras',
    'representacao', 'representação',
    'simbolo', 'símbolo', 'símbolos',
    'simbolo', 'simbolos',
    'sigilo', 'sigilos',
    'emblema', 'emblemas',
    'divisa', 'divisas',
    'insignia', 'insígnias',
    'distintivo', 'distintivos',
    'uniforme', 'uniformes',
    'farda', 'fardas',
    'traje', 'trajes',
    'vestuário', 'vestuario',
    'vestimenta', 'vestimentas',
    'roupa', 'roupas',
    'indumentaria', 'indumentária',
    'adorno', 'adornos',
    'joia', 'joias',
    'bijuteria', 'bijuterias',
    'perola', 'pérola', 'perolas', 'pérolas',
    'diamante', 'diamantes',
    'ouro', 'ouros',
    'prata', 'pratas',
    'bronze', 'bronzes',
    'cobre', 'cobres',
    'ferro', 'ferros',
    'aco', 'aço', 'acos', 'aços',
    'estanho', 'estanhos',
    'chumbo', 'chumbos',
    'mercurio', 'mercurio',
    'prata', 'pratas',
    'platina', 'platinas',
    'aluminio', 'alumínio',
    'zinco', 'zincos',
    'niquel', 'níquel',
    'estanho', 'estanhos',
    'liga', 'ligas',
    'mistura', 'misturas',
    'combinaçao', 'combinação',
    'mistura', 'misturas',
    'composto', 'compostos',
    'elemento', 'elementos',
    'substancia', 'substância', 'substancias',
    'materia', 'matéria', 'materias',
    'material', 'materiais',
    'corpo', 'corpos',
    'objecto', 'objectos', 'objeto', 'objetos',
    'coisa', 'coisas',
    'cousa', 'cousas',
    'entidade', 'entidades',
    'ser', 'seres',
    'pessoa', 'pessoas',
    'individuo', 'indivíduo', 'individuos',
    'homem', 'homens',
    'mulher', 'mulheres',
    'criança', 'criancas', 'crianças',
    'menino', 'meninos',
    'menina', 'meninas',
    'jovem', 'jovens',
    'adulto', 'adultos',
    'idoso', 'idosos',
    'velho', 'velhos', 'velha', 'velhas',
    'ancião', 'ancioes', 'anciãos',
    'anciana', 'anciãs',
    'crianca', 'criancas',
    'bebé', 'bebe', 'bebês',
    'recem-nascido', 'recém-nascido',
    'recém-nascida',
    'gémeo', 'gemeo', 'gêmeos', 'gemeos',
    'gémea', 'gemea', 'gêmeas', 'gemeas',
    'gémeos', 'gemeos',
    'gémeas', 'gemeas',
    'triplo', 'tripla',
    'quadruplo', 'quadruplos',
    'quintuplo', 'quintuplos',
    'sexuplo', 'sexuplos',
    'sextuplo', 'sextuplos',
    'setuplo', 'setuplos',
    'octuplo', 'octuplos',
    'nonuplo', 'nonuplos',
    'decuplo', 'decuplos',
    'duodécuplo',
    'centuplo', 'centuplos',
    'milhar', 'milhares',
    'milhão', 'milhões',
    'bilhão', 'bilhões',
    'trilhão', 'trilhões',
    'milha', 'milhas',
    'legua', 'leguas',
    'quilometro', 'quilômetro',
    'metro', 'metros',
    'centimetro', 'centímetro',
    'milimetro', 'milímetro',
    'jarda', 'jardas',
    'pé', 'pés',
    'polegada', 'polegadas',
    'palmo', 'palmos',
    'côvado', 'covado',
    'braça', 'braças',
    'braçada',
    'passo', 'passos',
    'trespasso',
    'salto', 'saltos',
    'pulo', 'pulos',
    'corrida', 'corridas',
    'caminhada', 'caminhadas',
    'marcha', 'marchas',
    'viagem', 'viagens',
    'passeio', 'passeios',
    'excursão', 'excursao',
    'tour', 'tours',
    'volta', 'voltas',
    'regresso', 'regressos',
    'retorno', 'retornos',
    'ida', 'idas',
    'chegada', 'chegadas',
    'partida', 'partidas',
    'saida', 'saídas',
    'entrada', 'entradas',
    'acesso', 'acessos',
    'ingresso', 'ingressos',
    'admissão', 'admissao',
    'entrada', 'entradas',
    'saída', 'saida',
    'saída', 'saidas',
    'despacho', 'despachos',
    'expediente', 'expedientes',
    'documento', 'documentos',
    'papel', 'papeis',
    'folha', 'folhas',
    'pagina', 'página', 'paginas',
    'livro', 'livros',
    'tomo', 'tomos',
    'volume', 'volumes',
    'fasciculo', 'fascículos',
    'fasc', 'fsc',
    'parte', 'partes',
    'secção', 'seccao', 'secções',
    'capitulo', 'capítulo', 'capitulos',
    'capítulo',
    'seccao', 'sessao',
    'secção', 'sessão',
    'artigo', 'artigos',
    'paragrafo', 'parágrafo',
    'parágrafo',
    'alinea', 'alínea',
    'inciso', 'incisos',
    'item', 'itens',
    'numero', 'números',
    'clausula', 'cláusula',
    'ponto', 'pontos',
    'virgula', 'vírgula',
    'ponto-final',
    'reticencias',
    'exclamacao',
    'interrogacao',
    'aspas',
    'parêntese',
    'colchete',
    'chave',
    'barra',
    'traço',
    'hífen',
    'sublinhado',
    'italico',
    'negrito',
    'sublinha',
    'maiuscula',
    'minuscula',
    'capital',
    'versal',
    'letra',
    'tipo',
    'fonte',
}

# Names that look like places or common words (should be excluded)
LOCATION_WORDS = {
    'villa', 'vila', 'igreja', 'igrejas', 'capella', 'capelas',
    'bispado', 'arquivo', 'distrito', 'freguesia', 'freguesias',
    'collegiada', 'collegiada', 'cemiterio', 'cemitério',
    'collegio', 'colégio', 'convento', 'mosteiro', 'ermida',
    'matriz', 'oratorio', 'oratório', 'parochia', 'paróquia',
    'ermida', 'capellao', 'capelão', 'sacristia',
    'santa', 'santo', 'santos', 'sancta', 'senhora',
    'padre', 'reverendo', 'vigario', 'vigário', 'cura', 'prior',
    'arcipreste', 'beneficiado', 'mordomo', 'juiz', 'escrivão',
    'encomendado', 'provisor', 'vigairo',
    'celorico', 'beira', 'guarda', 'portugal',
    'reinado', 'el-rei', 'magestade', 'majestade',
    'mes', 'mez', 'mezes', 'anno', 'annos', 'anos',
    'era', 'aos',
    'desta', 'deste', 'desse', 'dessa', 'nesta', 'neste',
    'assento', 'assentos', 'livro', 'livros', 'folhas', 'folha',
    'testamento', 'testamentos',
}

def extract_persons(raw_text):
    """Extract person names from HTR text - STRICT mode."""
    if not raw_text or len(raw_text.strip()) < 50:
        return []
    
    persons = []
    text = ' '.join(raw_text.split())
    
    def clean_name_parts(parts):
        cleaned = []
        for part in parts:
            part_lower = part.lower().strip('.,;:')
            if part_lower not in NOISE_WORDS and len(part) > 2:
                cleaned.append(part)
        return cleaned
    
    def try_add_name(parts):
        cleaned = clean_name_parts(parts)
        if len(cleaned) >= 2:
            nome = ' '.join(cleaned[:-1])[:100]
            apelido = cleaned[-1][:50]
            # Final validation: must have at least 2 words and first letter capitalized
            if len(nome.split()) >= 1 and nome[0].isupper() and apelido[0].isupper():
                persons.append({"nome": nome, "sobrenome": apelido})
                return True
        return False
    
    # 1. Very strict pattern: D. Nome (must have full name after D.)
    names_d = re.findall(r'D\.\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,4})', text)
    for name in names_d:
        if try_add_name(name.split()):
            return persons[:1]  # Return first valid result
    
    # 2. Obito/Oficio/Assento de + Name
    names_obito = re.findall(r'(?:Obito|Oficio|Assento|Livro)\s+(?:de|da|do)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,3})', text)
    for name in names_obito:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 3. Priest titles + Name
    titles = r'(?:Padre|Reverendo(?:\s+Padre)?)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,3})'
    names_priest = re.findall(titles, text)
    for name in names_priest:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 4. Title + Name (Encomendado, Vigario, Prior, etc.)
    titles2 = r'(?:Encomendado|Vigario|Vigário|Cura|Prior|Arcipreste|Beneficiado|Mordomo|Juiz|Escrivão|Provisor)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,3})'
    names_title = re.findall(titles2, text)
    for name in names_title:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 5. mulher/filho/filha de + Name
    names_family = re.findall(r'(?:mulher|filho|filha|viuva?|sobrinha?|afilhada?|sobrinho|afilhado)\s+de\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,2})', text)
    for name in names_family[:1]:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 6. meu/minha + relationship + Name
    names_family2 = re.findall(r'(?:meu|minha)\s+(?:sobrinho|sobrinha|afilhado|afilhada|filho|filha|irmao|irmaã|pai|mae)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,2})', text)
    for name in names_family2[:1]:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 7. Name de Name (surname pattern) - require at least 3 words with "de"
    names_surname = re.findall(r'(?:^|[\s,;])([A-ZÀ-Ú][a-zà-ú]+(?:\s+de\s+[A-ZÀ-Ú][a-zà-ú]+){1,2})', text)
    for name in names_surname[:1]:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 8. death event patterns with old spelling
    names_death = re.findall(r'(?:faleceo|falleceu|falece|faleçeo|morreo|morreu)\s+(?:o|a)?\s*([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,2})', text)
    for name in names_death[:1]:
        if try_add_name(name.split()):
            return persons[:1]
    
    return persons[:1]  # Return at most 1 person per record
