#!/usr/bin/env python3
"""
Update registos com nome='Desconhecido' na BD com nomes extraídos dos HTR já processados.
Uses strict extractor to avoid false positives like 'Villa', 'Igreja', etc.
"""
import os
import sys
import json
import re
import urllib.request
import urllib.error
from datetime import datetime

SUPABASE_URL = 'https://qljopxbxgflozrcdblrl.supabase.co'
SUPABASE_KEY = os.environ.get("SUPABASE_ANON_KEY", os.environ.get("SUPABASE_KEY", "sb_publishable_-oWYfk9uhb5DIByIe7xUhw_jb_touP1"))
INPUT_DIR = '/home/pxtkhw/projetos/obitos/output/htr_text'


NOISE_WORDS = {
    'villa', 'vila', 'igreja', 'igrejas', 'capella', 'capelas', 'collegiada',
    'bispado', 'arquivo', 'distrito', 'freguesia', 'freguesias',
    'cemiterio', 'cemitério', 'sepultura', 'sepultamento', 'sepultado',
    'assento', 'assentos', 'livro', 'livros', 'folhas', 'folha',
    'defuntos', 'corpo', 'morte', 'morto', 'morta',
    'sacramento', 'sacramentos', 'batismo', 'casamento', 'obito', 'óbito',
    'testamento', 'testamentos', 'herdeiro', 'herdeira', 'legado',
    'eram', 'desta', 'deste', 'desse', 'dessa', 'nesta', 'neste',
    'aos', 'era', 'anno', 'annos', 'anos', 'idade', 'meses', 'dias',
    'janeiro', 'fevereiro', 'março', 'marco', 'abril', 'maio', 'junho',
    'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro',
    'santa', 'santo', 'santos', 'sancta', 'senhora', 'senhor',
    'padre', 'reverendo', 'vigario', 'vigário', 'cura', 'prior',
    'arcipreste', 'beneficiado', 'mordomo', 'juiz', 'escrivão',
    'encomendado', 'provisor', 'vigairo',
    'matriz', 'collegio', 'colégio', 'convento', 'mosteiro',
    'ermida', 'cathedral', 'catedral', 'parochia', 'paróquia',
    'oratorio', 'oratório', 'capellao', 'capelão', 'coadjuctor',
    'coadjutor', 'sacristao', 'sacristã', 'sacristia',
    'celorico', 'celoricense', 'beirense', 'guarda',
    'portugal', 'reinado', 'el-rei', 'el rei',
    'magestade', 'majestade',
    'mes', 'mez', 'mezes',
    'irmaos', 'irmaãs', 'irmao', 'irmaã',
    'neto', 'neta', 'netos', 'netas',
    'sobrinho', 'sobrinha', 'sobrinhos', 'sobrinhas',
    'tio', 'tia', 'tios', 'tias',
    'avo', 'avos', 'avó', 'avô',
    'cunhado', 'cunhada', 'cunhados', 'cunhadas',
    'genro', 'nora',
    'padrasto', 'madrasta',
    'afilhado', 'afilhada', 'afilhados', 'afilhadas',
    'compadre', 'comadre',
    'vizinho', 'vizinha', 'vizinhos', 'vizinhas',
    'proximo', 'proxima', 'proximos', 'proximas',
    'parente', 'parentes',
    'familia', 'família', 'familias', 'famílias',
    'alma', 'almas',
    'casa', 'casas',
    'testador', 'testadora',
    'testamenteiro', 'testamenteira',
    'inventariante',
    'inventario', 'inventário',
    'partilha', 'partilhas',
    'herança', 'heranças',
    'legado', 'legados',
    'fogo', 'fogos',
    'lume', 'lumes',
    'domicilio', 'domicílio',
    'habitação', 'habitacao',
    'residencia', 'residência',
    'função', 'funcao',
    'serviço', 'servicos',
    'empréstimo',
    'divida', 'dividas',
    'deve', 'devem',
    'credor', 'credora', 'credores', 'credoras',
    'devedor', 'devedora', 'devedores', 'devedoras',
    'fiador', 'fiadora', 'fiadores', 'fiadoras',
    'aval', 'avais',
    'hipoteca', 'hipotecas',
    'penhor', 'penhores',
    'cauçao', 'caução',
    'caucao', 'caucões',
    'divida', 'dividas',
    'juros', 'juro',
    'amortizaçao', 'amortização',
    'prestaçao', 'prestação',
    'prazo', 'prazos',
    'vencimento', 'vencimentos',
    'mora', 'moras',
    'multa', 'multas',
    'coima', 'coimas',
    'taxa', 'taxas',
    'imposto', 'impostos',
    'contribuiçao', 'contribuição',
    'tributo', 'tributos',
    'direito', 'direitos',
    'dever', 'deveres',
    'obrigacao', 'obrigação',
    'obrigacoes', 'obrigações',
    'contrato', 'contratos',
    'acordo', 'acordos',
    'convençao', 'convenção',
    'tratado', 'tratados',
    'pacto', 'pactos',
    'pactuado',
    'ajuste', 'ajustes',
    'arranjo', 'arranjos',
    'combinacao', 'combinação',
    'combinaçao', 'combinações',
    'combinado',
    'acerto', 'acertos',
    'acertado',
    'resoluçao', 'resolução',
    'resolucao', 'resolucoes',
    'decisao', 'decisão',
    'decisoes', 'decisões',
    'determinaçao', 'determinação',
    'determinaçoes', 'determinações',
    'resolucao', 'resolucoes',
    'veredit', 'veredito',
    'sentenca', 'sentença',
    'sentencas', 'sentenças',
    'julgamento', 'julgamentos',
    'audiência', 'audiencia',
    'audiencias', 'audiências',
    'tribunal', 'tribunais',
    'juizo', 'juízo',
    'juizos', 'juízos',
    'vara', 'varas',
    'comarca', 'comarcas',
    'distrito', 'distritos',
    'concelho', 'concelhos',
    'freguesia', 'freguesias',
    'cidade', 'cidades',
    'vila', 'vilas',
    'alegria', 'alegrias',
    'tristeza', 'tristezas',
    'dor', 'dores',
    'sofrimento', 'sofrimentos',
    'alegria', 'alegrias',
    'prazer', 'praceres',
    'gozo', 'gozos',
    'contentamento', 'contentamentos',
    'satisfaçao', 'satisfação',
    'decepçao', 'decepção',
    'desilusao', 'desilusão',
    'desapontamento',
    'frustraçao', 'frustração',
    'desespero', 'desesperos',
    'esperança', 'esperanca',
    'esperancas', 'esperanças',
    'confiança', 'confianca',
    'confiancas', 'confianças',
    'fé', 'fe', 'fés',
    'crença', 'crencas',
    'crença', 'crenças',
    'religiao', 'religião',
    'religioes', 'religiões',
    'fé', 'fe',
    'crença', 'crenças',
    'doutrina', 'doutrinas',
    'dogma', 'dogmas',
    'culto', 'cultos',
    'rito', 'ritos',
    'ritual', 'rituais',
    'cerimonia', 'cerimónia',
    'festa', 'festas',
    'celebração', 'celebracoes',
    'memoria', 'memória',
    'memorias', 'memórias',
    'recordaçao', 'recordação',
    'recordacoes', 'recordações',
    'lembrança', 'lembrancas',
    'saudade', 'saudades',
    'nostalgia', 'nostalgias',
    'amor', 'amores',
    'ódio', 'odio',
    'ódios', 'odios',
    'inveja', 'invejas',
    'ciume', 'ciume',
    'cIUMES', 'ciumes',
    'ciúme', 'ciumes',
    'cIUMES',
    'raiva', 'raivas',
    'ira', 'iras',
    'ódio', 'ódios',
    'desprezo', 'desprezos',
    'desdém', 'desdem',
    'desdenho',
    'menosprezo',
    'depreciacao',
    'depreciacao',
    'desvalorizaçao',
    'desvalorizacao',
    'desconsideracao',
    'humildade',
    'modestia',
    'simplicidade',
    'pobreza',
    'riqueza',
    'fortuna',
    'fortunas',
    'patrimonio',
    'património',
    'patrimonios', 'patrimónios',
    'herança', 'herancas',
    'legado', 'legados',
    'sucessao', 'sucessão',
    'sucessões', 'sucessos',
    'sucessor', 'sucessora',
    'sucessores', 'sucessoras',
    'herdeiro', 'herdeira',
    'herdeiros', 'herdeiras',
    'legatario', 'legatário',
    'legatarios', 'legatários',
    'legatária', 'legatárias',
    'testamenteiro', 'testamenteira',
    'inventariante',
    'inventario', 'inventário',
    'inventarios', 'inventários',
    'partilha', 'partilhas',
    'divisao', 'divisão',
    'divisoes', 'divisões',
    'rateio', 'rateios',
    'partilhar',
    'dividir',
    'distribuir',
    'distribuicao',
    'distribuição',
    'distribuicoes', 'distribuições',
    'repartir',
    'reparticao',
    'repartição',
    'reparticoes',
    'repartições',
    'ceder',
    'cedencia',
    'cedências',
    'cedencias',
    'transmissao',
    'transmissão',
    'transmissoes', 'transmissões',
    'transferencia',
    'transferência',
    'transferencias', 'transferências',
    'tranferir',
    'passar',
    'passagem',
    'passagens',
    'transiçao',
    'transição',
    'transiçoes', 'transições',
    'passagem',
    'mudança',
    'mudanca',
    'mudanças',
    'mudancas',
    'muança',
    'variação',
    'variacao',
    'variacoes', 'variações',
    'mudado',
    'mudada',
    'mudados',
    'mudadas',
    'alterado',
    'alterada',
    'alterados',
    'alteradas',
    'modificado',
    'modificada',
    'modificados',
    'modificadas',
    'transformado',
    'transformada',
    'transformados',
    'transformadas',
    'convertido',
    'convertida',
    'convertidos',
    'convertidas',
    'trocado',
    'trocada',
    'trocados',
    'trocadas',
    'trocado',
    'trocada',
    'trocados',
    'trocadas',
    'substituido',
    'substituida',
    'substituidos',
    'substituidas',
    'substituir',
    'substituicao',
    'substituição',
    'substituicoes', 'substituições',
    'substituto',
    'substitutos',
    'substituta',
    'substitutas',
    'sucedaneo',
    'sucedâneo',
    'sucedaneos', 'sucedâneos',
    'alternativa',
    'alternativas',
    'opçao',
    'opção',
    'opcoes', 'opções',
    'opçao',
    'escolha',
    'escolhas',
    'escolher',
    'eleger',
    'eleiçao',
    'eleição',
    'eleicoes', 'eleições',
    'voto', 'votos',
    'votar',
    'eleitor',
    'eleitores',
    'eleitora',
    'eleitoras',
    'candidato',
    'candidatos',
    'candidata',
    'candidatas',
    'candidatura',
    'candidaturas',
    'eleiçao',
    'plebiscito',
    'referendo',
    'referendos',
    'votaçao',
    'votacao',
    'votacoes', 'votações',
    'apuracao',
    'apuração',
    'apuracao',
    'apuracao',
    'resultado',
    'resultados',
    'vitoria',
    'vitoria',
    'derrota',
    'derrotas',
    'empate',
    'empates',
    'vencedor',
    'vencedores',
    'perdedor',
    'perdedores',
    'ganhador',
    'ganhadores',
    'ganhadora',
    'ganhadoras',
    'prémio', 'premio',
    'premios', 'prêmios',
    'prémios',
    'recompensa',
    'recompensas',
    'galardao',
    'galardao',
    'galardões',
    'distincao',
    'distinção',
    'distincoes', 'distinções',
    'honraria',
    'honrarias',
    'homenagem',
    'homenagens',
    'preito',
    'preitos',
    'laurea',
    'laureas',
    'coroa',
    'coroas',
    'trofeu',
    'trofeus',
    'trofeu',
    'medalha',
    'medalhas',
    'diploma',
    'diplomas',
    'certificado',
    'certificados',
    'atestado',
    'atestados',
    'atestado',
    'atestados',
    'certidao',
    'certidão',
    'certidoes', 'certidões',
    'documento',
    'documentos',
    'papel',
    'papeis',
    'escrito',
    'escrita',
    'escritos',
    'escritas',
    'autografo',
    'autógrafo',
    'assinatura',
    'assinaturas',
    'rubrica',
    'rubricas',
    'signo',
    'signos',
    'selo',
    'selos',
    'sinete',
    'sinetes',
    'carimbo',
    'carimbos',
    'estampa',
    'estampas',
    'marca',
    'marcas',
    'logotipo',
    'logotipos',
    'emblema',
    'emblemas',
    'insignia',
    'insígnias',
    'distintivo',
    'distintivos',
    'uniforme',
    'uniformes',
    'farda',
    'fardas',
    'traje',
    'trajes',
    'vestuario',
    'vestuário',
    'vestimenta',
    'vestimentas',
    'indumentaria',
    'indumentária',
    'adorno',
    'adornos',
    'joia',
    'joias',
    'bijuteria',
    'bijuterias',
    'pulseira',
    'pulseiras',
    'anel',
    'aneis',
    'anéis',
    'brinco',
    'brincos',
    'colar',
    'colares',
    'corrente',
    'correntes',
    'fio',
    'fios',
    'perola',
    'pérola',
    'perolas', 'pérolas',
    'diamante',
    'diamantes',
    'ouro',
    'ouros',
    'prata',
    'pratas',
    'bronze',
    'bronzes',
    'cobre', 'cobres',
    'ferro',
    'ferros',
    'aco', 'aço',
    'estanho',
    'estanhos',
    'chumbo',
    'chumbos',
    'mercurio',
    'mercurios',
    'mercurio',
    'platina',
    'platinas',
    'aluminio',
    'alumínio',
    'zinco',
    'zincos',
    'niquel',
    'níquel',
    'liga',
    'ligas',
    'mistura',
    'misturas',
    'composto',
    'compostos',
    'elemento',
    'elementos',
    'substancia',
    'substância',
    'substancias', 'substâncias',
    'materia',
    'matéria',
    'materias', 'matérias',
    'material',
    'materiais',
    'corpo',
    'corpos',
    'objecto',
    'objectos',
    'objeto',
    'objetos',
    'coisa',
    'coisas',
    'cousa',
    'cousas',
    'entidade',
    'entidades',
    'ser',
    'seres',
    'pessoa',
    'pessoas',
    'individuo',
    'indivíduo',
    'individuos',
    'homem',
    'homens',
    'mulher',
    'mulheres',
    'criança',
    'criancas',
    'crianças',
    'menino',
    'meninos',
    'menina',
    'meninas',
    'jovem',
    'jovens',
    'adulto',
    'adultos',
    'idoso',
    'idosos',
    'velho',
    'velhos',
    'velha',
    'velhas',
    'ancião',
    'anciãos',
    'anciana',
    'anciãs',
    'crianca',
    'criancas',
    'bebé',
    'bebe',
    'bebês',
    'bebes',
    'recém-nascido',
    'reciém-nascida',
    'gémeo',
    'gemeo',
    'gêmeos',
    'gemeos',
    'gémeos',
    'gémea',
    'gemea',
    'gêmeas',
    'gemeas',
    'gémeas',
    'gémeas',
    'gemeas',
    'triplo',
    'tripla',
    'quadruplo',
    'quadruplos',
    'quintuplo',
    'quintuplos',
    'sexuplo',
    'sexuplos',
    'sextuplo',
    'sextuplos',
    'setuplo',
    'setuplos',
    'octuplo',
    'octuplos',
    'nonuplo',
    'nonuplos',
    'decuplo',
    'decuplos',
    'duodécuplo',
    'centuplo',
    'centuplos',
    'milhar',
    'milhares',
    'milhão',
    'milhões',
    'bilhão',
    'bilhões',
    'trilhão',
    'trilhões',
    'milha',
    'milhas',
    'legua',
    'leguas',
    'quilometro',
    'quilômetro',
    'metro',
    'metros',
    'centimetro',
    'centímetro',
    'milimetro',
    'milímetro',
    'jarda',
    'jardas',
    'pé',
    'pés',
    'polegada',
    'polegadas',
    'palmo',
    'palmos',
    'côvado',
    'covado',
    'braça',
    'braças',
    'passo',
    'passos',
    'salto',
    'saltos',
    'corrida',
    'corridas',
    'caminhada',
    'caminhadas',
    'marcha',
    'marchas',
    'viagem',
    'viagens',
    'passeio',
    'passeios',
    'volta',
    'voltas',
    'regresso',
    'regressos',
    'retorno',
    'retornos',
    'chegada',
    'chegadas',
    'partida',
    'partidas',
    'saída',
    'saidas',
    'entrada',
    'entradas',
    'acesso',
    'acessos',
    'ingresso',
    'ingressos',
    'saida',
    'saída',
    'saidas',
    'despacho',
    'despachos',
    'expediente',
    'expedientes',
    'documento',
    'documentos',
    'papel',
    'papeis',
    'pagina',
    'página',
    'tomo',
    'tomos',
    'fasciculo',
    'fascículos',
    'parte',
    'partes',
    'artigo',
    'artigos',
    'ponto',
    'pontos',
    'letra',
    'letras',
    'reticencias',
    'exclamacao',
    'exclamação',
    'interrogacao',
    'interrogação',
    'aspas',
    'parêntese',
    'colchete',
    'barra',
    'traço',
    'hífen',
    'sublinhado',
    'maiuscula',
    'maiúscula',
    'minuscula',
    'minúscula',
    'capital',
    'versal',
    'tipo',
    'fonte',
    'imprensa',
    'estamparia',
    'oficina',
    'oficinas',
    'trabalho',
    'trabalhos',
    'obra',
    'obras',
    'servico',
    'serviços',
    'servicos',
    'emprego',
    'empregos',
    'cargo',
    'cargos',
    'posta',
    'postas',
    'promocao',
    'promoção',
    'promocoes',
    'subida',
    'subidas',
    'cair',
    'levantar',
    'levantou',
    'pegar',
    'soltar',
    'soltou',
    'segurar',
    'segurou',
    'largar',
    'largou',
    'abrir',
    'abriu',
    'fechar',
    'fechou',
    'entrar',
    'entrou',
    'ficar',
    'ficou',
    'andar',
    'anda',
    'passar',
    'passou',
    'chegar',
    'chegou',
    'partir',
    'partiu',
    'correr',
    'corre',
    'saltar',
    'saltou',
    'pular',
    'pulou',
    'cantar',
    'cantou',
    'tocar',
    'tocou',
    'ouvir',
    'ouviu',
    'ver',
    'viu',
    'olhar',
    'olhou',
    'corpo',
    'casa',
    'domicilio',
    'domicílio',
}

def clean_name(parts):
    cleaned = []
    for part in parts:
        part_lower = part.lower().strip('.,;:')
        if part_lower not in NOISE_WORDS and len(part) > 2:
            cleaned.append(part)
    return cleaned

def extract_persons(raw_text):
    persons = []
    text = ' '.join(raw_text.split())
    
    def try_add_name(parts):
        cleaned = clean_name(parts)
        if len(cleaned) >= 2:
            nome = ' '.join(cleaned[:-1])[:100]
            apelido = cleaned[-1][:50]
            if nome and apelido and nome[0].isupper() and apelido[0].isupper():
                persons.append({'nome': nome, 'sobrenome': apelido})
                return True
        return False
    
    # 1. Very strict pattern: D. Nome (must have full name after D.)
    names_d = re.findall(r'D\.\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,4})', text)
    for name in names_d:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 2. Obito/Oficio/Assento de + Name
    names_obito = re.findall(r'(?:Obito|Oficio|Assento|Livro)\s+(?:de|da|do)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,3})', text)
    for name in names_obito:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 3. Priest titles + Name
    titles = r'(?:Padre|Reverendo(?:\s+Padre)?)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,3})'
    names_priest = re.findall(titles, text)
    for name in names_priest:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 4. Title + Name (Encomendado, Vigario, Prior, etc.)
    titles2 = r'(?:Encomendado|Vigario|Vigário|Cura|Prior|Arcipreste|Beneficiado|Mordomo|Juiz|Escrivão|Provisor)\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,3})'
    names_title = re.findall(titles2, text)
    for name in names_title:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 5. mulher/filho/filha de + Name
    names_family = re.findall(r'(?:mulher|filho|filha|viuva?|sobrinha?|afilhada?|sobrinho|afilhado)\s+de\s+([A-ZÀ-Ú][a-zà-ú]+(?:\s+(?:de\s+|da\s+|do\s+)?[A-ZÀ-Ú][a-zà-ú]+){1,2})', text)
    for name in names_family[:1]:
        if try_add_name(name.split()):
            return persons[:1]
    
    # 6. Name de Name (surname pattern) - require at least 2 "de" connections
    names_surname = re.findall(r'(?:^|[\s,;])([A-ZÀ-Ú][a-zà-ú]+(?:\s+de\s+[A-ZÀ-Ú][a-zà-ú]+){1,2})', text)
    for name in names_surname[:1]:
        if try_add_name(name.split()):
            return persons[:1]
    
    return persons[:1]


def supabase_patch(record_id, data):
    url = f"{SUPABASE_URL}/rest/v1/pessoas?id=eq.{record_id}"
    payload = json.dumps(data).encode()
    headers = {
        'Content-Type': 'application/json',
        'apikey': SUPABASE_KEY,
        'Authorization': f'Bearer {SUPABASE_KEY}',
        'Prefer': 'return=minimal'
    }
    req = urllib.request.Request(url, data=payload, headers=headers, method='PATCH')
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return True
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()[:200]
        print(f"  Erro HTTP {e.code}: {error_body}")
        return False
    except Exception as e:
        print(f"  Erro: {e}")
        return False

def get_unknown_records(limit=1000):
    url = f"{SUPABASE_URL}/rest/v1/pessoas?select=id,file_id,nome&nome=eq.Desconhecido&limit={limit}"
    headers = {'apikey': SUPABASE_KEY, 'Authorization': f'Bearer {SUPABASE_KEY}'}
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read())
    except Exception as e:
        print(f"Erro ao buscar registos: {e}")
        return []

def main():
    print("=== Actualizar registos 'Desconhecido' ===\n")
    
    records = get_unknown_records()
    print(f"Registos 'Desconhecido': {len(records)}")
    
    updated = 0
    skipped = 0
    errors = 0
    
    for i, rec in enumerate(records):
        file_id = rec.get('file_id')
        if not file_id:
            skipped += 1
            continue
        
        json_path = os.path.join(INPUT_DIR, f"{file_id}.json")
        if not os.path.exists(json_path):
            skipped += 1
            if (i + 1) % 50 == 0:
                print(f"  Progresso: {i+1}/{len(records)} (actualizados: {updated}, ignorados: {skipped})")
            continue
        
        try:
            with open(json_path) as f:
                data = json.load(f)
            raw = data.get('raw_text', data.get('transcription', ''))
            
            persons = extract_persons(raw)
            if persons:
                new_name = persons[0]['nome']
                if supabase_patch(rec['id'], {'nome': new_name}):
                    updated += 1
                    if (i + 1) % 25 == 0:
                        print(f"  {i+1}/{len(records)}: {rec['file_id']} -> {new_name}")
                else:
                    errors += 1
            else:
                skipped += 1
        except Exception as e:
            errors += 1
        
        if (i + 1) % 50 == 0:
            print(f"  Progresso: {i+1}/{len(records)} (actualizados: {updated}, ignorados: {skipped}, erros: {errors})")
    
    print(f"\n=== Concluído ===")
    print(f"Actualizados: {updated}")
    print(f"Ignorados: {skipped}")
    print(f"Erros: {errors}")

if __name__ == '__main__':
    main()
